version: '2.0'
services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - "./node/app:/src/app"
    ports:
      - "8080:3000"
    links:
      - couchdb
  
  couchdb:
    image: couchdb:1.6.1
    build:
      context: ./couchdb
      dockerfile: Dockerfile
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - "couchdb_data:/var/lib/couchdb"
    ports:
      - "5984:5984"

volumes:
  couchdb_data:
